# Generated by Django 4.1.6 on 2023-02-11 13:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=221)),
                ('birthday', models.DateTimeField()),
                ('location', models.CharField(max_length=221)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('is_empty', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('narxi', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laborant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Diseased_to_Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.diseased')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=250)),
                ('open_time', models.DateTimeField(auto_now_add=True)),
                ('close_time', models.DateTimeField()),
                ('diseased', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.diseased')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.room')),
            ],
        ),
    ]
