# Generated by Django 4.1.6 on 2023-02-13 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_diseased_room_laboratory_diseased_to_laboratory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseased',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 13, 9, 6, 3, 447368, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diseased',
            name='birthday',
            field=models.DateField(),
        ),
    ]
