# Generated by Django 4.1.6 on 2023-02-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_diseased_order_time_alter_diseased_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseased',
            name='spesialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.doctor'),
        ),
    ]
