# Generated by Django 4.1.6 on 2023-02-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_diseased_spesialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseased',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='diseased',
            name='spesialist',
        ),
    ]
