# Generated by Django 4.1.6 on 2023-02-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_chamber_diseased'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
