# Generated by Django 4.1.6 on 2023-02-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_chamber_days_alter_chamber_close_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='close_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='days',
            field=models.IntegerField(),
        ),
    ]
