# Generated by Django 4.1.6 on 2023-02-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_chamber_is_created_alter_chamber_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
