# Generated by Django 4.1.6 on 2023-02-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamber',
            name='is_created',
        ),
    ]
