# Generated by Django 4.1.6 on 2023-02-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_remove_chamber_is_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber',
            name='days',
            field=models.PositiveIntegerField(),
        ),
    ]
